version: "3.9"
   
services:
  db:
    build:
      context: ./docker/
      dockerfile: db.Dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=onlease
  web:
    restart: always
    build:
      context: ./docker/
      dockerfile: web.Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - BASE_URL=0.0.0.0:8000
      - GOOGLE_MAPS_API_KEY= ${GOOGLE_MAPS_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - NG_ROK=${NG_ROK}
      - USE_NG_ROK:=${USE_NG_ROK}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - TF_APIKEY=${TF_APIKEY}