version: "3.9"
   
services:
    db:
        image: postgres
        volumes:
            - ./var/pgdata/test:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=onlease
        networks:
            - onlease_test
    web:
        restart: always
        build:
            context: ./
            dockerfile: backend/web.Dockerfile
        volumes:
            - ./backend:/code
            - static_data:/vol/static
            - ./backend/media:/vol/media
        depends_on:
            - db
        env_file:
            - .env
        environment:
            - DEBUG=0
        networks:
            - onlease_test
    nginx:
        restart: always
        build:
            context: ./
            dockerfile: nginx/nginx.Dockerfile
        ports:
            - "8002:8000"
        volumes:
            - static_data:/vol/static
            - ./backend/media:/vol/media
        depends_on:
            - web
        networks:
            - onlease_test

volumes:
    static_data:

networks:
    onlease_test:
        driver: bridge
