version: "3.9"
   
services:
    test_db:
        restart: always
        build:
            context: ./
            dockerfile: docker/db.Dockerfile
        volumes:
            - ./var/test/pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=onlease
    test_web:
        restart: always
        build:
            context: ./
            dockerfile: docker/web.Dockerfile
        volumes:
            - .:/code
            - static_data:/vol/test/static
            - static_data:/vol/test/media
        ports:
            - "8000:8000"
        depends_on:
            - test_db
        environment:
            - DEBUG=0
            - BASE_URL=${BASE_URL}
            - GOOGLE_MAPS_API_KEY= ${GOOGLE_MAPS_API_KEY}
            - SECRET_KEY=${SECRET_KEY}
            - NG_ROK=${NG_ROK}
            - USE_NG_ROK=${USE_NG_ROK}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - TF_APIKEY=${TF_APIKEY}
            - STATIC_ROOT=/vol/test/static
            - MEDIA_ROOT=/vol/test/media
    test_nginx:
        restart: always
        build:
            context: ./
            dockerfile: docker/test.nginx.Dockerfile
        ports:
            - "8002:8000"
        volumes:
            - static_data:/vol/test/static
        depends_on:
            - test_web

volumes:
    static_data:
