version: "3.9"
   
services:
    db:
        restart: always
        build:
            context: ./
            dockerfile: docker/db.Dockerfile
        volumes:
            - ./var/prod/pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=onlease
    web:
        restart: always
        build:
            context: ./
            dockerfile: docker/web.Dockerfile
        volumes:
            - .:/code
            - static_data:/vol/static
            - static_data:/vol/media
        depends_on:
            - db
        environment:
            - DEBUG=0
            - BASE_URL=${BASE_URL}
            - GOOGLE_MAPS_API_KEY= ${GOOGLE_MAPS_API_KEY}
            - SECRET_KEY=${SECRET_KEY}
            - NG_ROK=${NG_ROK}
            - USE_NG_ROK=${USE_NG_ROK}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - TF_APIKEY=${TF_APIKEY}
            - STATIC_ROOT=/vol/static
            - MEDIA_ROOT=/vol/media
    nginx:
        restart: always
        build:
            context: ./
            dockerfile: docker/prod.nginx.Dockerfile
        ports:
            - "8001:8000"
        volumes:
            - static_data:/vol/static
        depends_on:
            - web

volumes:
    static_data:
