version: "3.9"
   
services:
    db:
        image: postgres
        volumes:
            - ./var/pgdata/test:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=onlease
        networks:
            - onlease_test
    web:
        restart: always
        build:
            context: ./
            dockerfile: docker/web.Dockerfile
        volumes:
            - .:/code
            - static_data:/vol/static
            - static_data:/vol/media
        depends_on:
            - db
        environment:
            - DEBUG=0
            - BASE_URL=${BASE_URL}
            - GOOGLE_MAPS_API_KEY= ${GOOGLE_MAPS_API_KEY}
            - SECRET_KEY=${SECRET_KEY}
            - NG_ROK=${NG_ROK}
            - USE_NG_ROK=${USE_NG_ROK}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USER=${DB_USER}
            - TF_APIKEY=${TF_APIKEY}
            - SUPERUSER_MOBILE=${SUPERUSER_MOBILE}
            - SUPERUSER_EMAIL=${SUPERUSER_MOBILE}
            - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
            - INSTAMOJO_API_KEY=${INSTAMOJO_API_KEY}
            - INSTAMOJO_AUTH_KEY=${INSTAMOJO_AUTH_KEY}
            - INSTAMOJO_SALT=${INSTAMOJO_SALT}
            - INSTAMOJO_ENDPOINT=${INSTAMOJO_ENDPOINT}
            - TWILIO_TOKEN=${TWILIO_TOKEN}
            - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
            - GMAIL_EMAIL=${GMAIL_EMAIL}
            - GMAIL_PASSWORD=${GMAIL_PASSWORD}
            - TEXTLOCAL_APIKEY=${TEXTLOCAL_APIKEY}
            - MSG91_AUTH_KEY=${MSG91_AUTH_KEY}
        networks:
            - onlease_test
    nginx:
        restart: always
        build:
            context: ./
            dockerfile: docker/nginx.Dockerfile
        ports:
            - "8002:8000"
        volumes:
            - static_data:/vol/static
        depends_on:
            - web
        networks:
            - onlease_test

volumes:
    static_data:

networks:
    onlease_test:
        driver: bridge
