# Generated by Django 2.2.13 on 2022-02-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='payment_gateway_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
