# Generated by Django 2.0.3 on 2019-01-04 21:17

import apps.image.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to=apps.image.models.image_upload_path)),
                ('image_thumbnail', models.ImageField(upload_to=apps.image.models.image_upload_path)),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to=apps.image.models.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tag', models.CharField(choices=[('0', 'Bedroom'), ('1', 'Hall'), ('2', 'Balcony'), ('3', 'Living Room'), ('4', 'Entrance'), ('5', 'Kitchen'), ('6', 'Bathroom'), ('7', 'Building'), ('8', 'Floor'), ('9', 'Outside View'), ('10', 'Other'), ('11', 'Dining Room')], max_length=2, null=True)),
                ('tag_other', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
