# Generated by Django 2.0.3 on 2018-07-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='tag',
            field=models.CharField(choices=[('B', 'Bedroom'), ('H', 'H'), ('BA', 'Balcony'), ('LR', 'Living Room'), ('E', 'Entrance'), ('K', 'Kitchen'), ('BR', 'Bathroom'), ('BU', 'Building'), ('F', 'Floor'), ('OU', 'Outside View'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
