# Generated by Django 2.0.3 on 2018-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20180901_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='tag',
            field=models.CharField(choices=[('0', 'Bedroom'), ('1', 'Hall'), ('2', 'Balcony'), ('3', 'Living Room'), ('4', 'Entrance'), ('5', 'Kitchen'), ('6', 'Bathroom'), ('7', 'Building'), ('8', 'Floor'), ('9', 'Outside View'), ('10', 'Other'), ('11', 'Dining Room')], max_length=2, null=True),
        ),
    ]
