# Generated by Django 2.0.3 on 2018-07-18 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z0-9-\\._]+@[a-zA-Z]+\\.[a-zA-Z]{1,3}')]),
        ),
    ]
