# Generated by Django 2.0.3 on 2018-04-26 00:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7903c942-094e-4c9d-a56d-425dd5e1aa25')),
        ),
    ]
