# Generated by Django 2.0.3 on 2018-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sharedproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedproperty',
            name='owner_number',
            field=models.CharField(default='9899761236', max_length=16),
            preserve_default=False,
        ),
    ]
