# Generated by Django 2.0.3 on 2018-05-06 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_no_times_not_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number_alternate1',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator('^[789][0-9]{9}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number_alternate2',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator('^[789][0-9]{9}$')]),
        ),
    ]
