# Generated by Django 2.0.3 on 2018-04-26 00:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180426_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e4c8b806-3e99-41eb-afde-3329cbcc0ebf')),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Password should be atleast of 8 charaters. It should consists of atleast one digit, one small alphabet and one capital alphabet.', max_length=100, validators=[django.core.validators.RegexValidator('^(?=[^0-9]*[0-9])[0-9a-zA-Z?\\/.,<>():;\'"\\[\\]{}~!@#$%^&*-_+]*$', message='Password must contain at least one digit.'), django.core.validators.RegexValidator('^(?=[^a-z]*[a-z])[0-9a-zA-Z?\\/.,<>():;\'"\\[\\]{}~!@#$%^&*-_+]*$', message='Password must contain at least one lower case letter.'), django.core.validators.RegexValidator('^(?=[^A-Z]*[A-Z])[0-9a-zA-Z?\\/.,<>():;\'"\\[\\]{}~!@#$%^&*-_+]*$', message='Password must contain at least one upper case letter.')]),
        ),
    ]
