# Generated by Django 2.0.3 on 2018-11-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sharedproperty_owner_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenumber',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
