# Generated by Django 2.0.3 on 2018-04-27 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180426_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumber',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1db09378-9538-4a85-8424-a71dd66c50a9')),
        ),
    ]
