# Generated by Django 2.0.3 on 2018-11-30 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0018_auto_20181130_2056'),
        ('user', '0004_auto_20181117_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_properties',
            field=models.ManyToManyField(related_name='favorite_of', to='lodging.CommonlyUsedLodgingModel'),
        ),
        migrations.AlterField(
            model_name='mobilenumber',
            name='value',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[789][0-9]{9}$', message='Enter a valid mobile number.')]),
        ),
    ]
