# Generated by Django 2.2.13 on 2021-04-22 00:07

from django.db import migrations
from django.db import models


def add_data(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for user in User.objects.all():
        if user.is_superuser:
            user.user_type = '2'
        else:
            user.user_type = '0'
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210415_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('0', 'Tenant'), ('1', 'Owner'), ('2', 'Admin')], default='0', max_length=1),
        ),
        migrations.RunPython(add_data)
    ]
