# Generated by Django 2.2.13 on 2021-04-23 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210124_0153'),
        ('user', '0005_auto_20210422_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('latlng', models.CharField(default='', max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='locations.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
