# Generated by Django 2.0.3 on 2018-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['state'], name='locations_l_state_93f5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['state', 'district'], name='locations_l_state_a9aa60_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['state', 'district', 'region'], name='locations_l_state_796fb8_idx'),
        ),
    ]
