# Generated by Django 2.0.3 on 2018-04-30 15:48

from django.db import migrations
import csv

def add_data(apps, schema_editor):
    Location = apps.get_model('locations','Location')
    filename = 'All_India_pincode_data_26022018.csv'
    file_data = csv.DictReader(open(filename,'r',errors='ignore'))
    for row in file_data:
        Location.objects.create(
            state=row['statename'],
            district=row['districtname'],
            region=row['officename'].split(' '+row['officetype'])[0],
            pincode=row['pincode']
        )

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
