# Generated by Django 2.0.3 on 2018-05-13 14:49

from django.db import migrations
import csv
# from multiprocessing import Process
import threading
import time
from django.db import connection

def add_data(apps, schema_editor):
    State = apps.get_model('locations', 'State')
    District = apps.get_model('locations', 'District')
    Region = apps.get_model('locations', 'Region')
    Pincode = apps.get_model('locations', 'Pincode')
    thread_list = []
    filename = 'All_India_pincode_data_26022018.csv'
    file_data = csv.DictReader(open(filename,'r',errors='ignore'))
    count=0
    for row in file_data:
        count+=1
        print(count)
        state=row['statename']
        district=row['districtname']
        region=row['officename'].split(' '+row['officetype'])[0]
        pincode=row['pincode']
        state_object = State.objects.get_or_create(name=state)
        district_object = District.objects.get_or_create(
            name=district,
            state=state_object[0]   
        )
        pincode_object = Pincode.objects.get_or_create(
            value=pincode,
            defaults={'district':district_object[0],'state':state_object[0]}
        )
        Region.objects.get_or_create(
            name=region,
            district=district_object[0],
            state=state_object[0],
            defaults={'pincode':pincode_object[0]}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
