# Generated by Django 2.2.13 on 2021-01-24 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodging', '0002_auto_20210124_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingTransaction',
            fields=[
                ('status', models.CharField(choices=[('0', 'Success'), ('1', 'Pending'), ('2', 'Cancelled'), ('3', 'Failed'), ('4', 'Refunded')], default='1', max_length=1)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_request_id', models.CharField(default='', max_length=40)),
                ('payment_id', models.CharField(default='', max_length=40)),
                ('payment_gateway', models.CharField(choices=[('0', 'Instamojo')], default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('payment_gateway_fees', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(default='', max_length=300)),
                ('trans_id', models.CharField(editable=False, max_length=60, primary_key=True, serialize=False)),
                ('lodging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='lodging.Lodging')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodgingtransactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
