# Generated by Django 2.0.3 on 2018-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='2CVkSC5j4hfgUiBnkAnn1uGw1wFtFXobTWSV0GU7HQ', editable=False, max_length=100, unique=True),
        ),
    ]
