# Generated by Django 2.0.3 on 2018-10-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20181001_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='ya3EP0eRZIvUwvWL92bLEXV4byNfj2PMo45lDnQ71j', editable=False, max_length=100, unique=True),
        ),
    ]
