# Generated by Django 2.0.3 on 2018-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_lodgingtransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='b4Y9b2mFkSmRzmAa', editable=False, max_length=40, unique=True),
        ),
    ]
