# Generated by Django 2.0.3 on 2021-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_lodgingtransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='drqB5fWnVaKFhyUEUTG6s14FEkkba3h0OYmsAm8uPO', editable=False, max_length=100, unique=True),
        ),
    ]
