# Generated by Django 2.0.3 on 2019-01-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_lodgingtransaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='3Xz1rHPmflx4OOGwuKLLU1sDB6jqThYruYASH4q5DH', editable=False, max_length=100, unique=True),
        ),
    ]
