# Generated by Django 2.0.3 on 2018-05-05 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_lodgingtransaction_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingtransaction',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgingtransaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
