# Generated by Django 2.0.3 on 2018-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180505_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodgingtransaction',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='amount_paid',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
