# Generated by Django 2.0.3 on 2019-02-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190128_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='ETPgJhikDKhcshlmgU3Nnol4tMlS5ebVDXOX5eB6lb', editable=False, max_length=100, unique=True),
        ),
    ]
