# Generated by Django 2.0.3 on 2018-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_lodgingtransaction_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='w34pRXuQZkRWijjG', editable=False, max_length=40, unique=True),
        ),
    ]
