# Generated by Django 2.0.3 on 2018-10-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20181006_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='TsiMCkCwMgeGHlqV3bUwuoEpRdy1GB0jSs4iuGg7lS', editable=False, max_length=100, unique=True),
        ),
    ]
