# Generated by Django 2.0.3 on 2021-01-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210113_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='lJBIn8SQqv7mI8SE2IHqzSadzjDQG6lWrlyIcBthBJ', editable=False, max_length=100, unique=True),
        ),
    ]
