# Generated by Django 2.0.3 on 2018-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180522_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='3S5uJ8QPyite72Fr', editable=False, max_length=40, unique=True),
        ),
    ]
