# Generated by Django 2.0.3 on 2021-01-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210117_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='SZ4zlAQj5SG0P0iexp74nAWkJm0p1t3pd00EF5OuyI', editable=False, max_length=100, unique=True),
        ),
    ]
