# Generated by Django 2.0.3 on 2019-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20190202_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='NVs3QH5QMgYxxF4uscWKTTqRT9ea6n615HNJQjDLFB', editable=False, max_length=100, unique=True),
        ),
    ]
