# Generated by Django 2.0.3 on 2018-10-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20181008_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='JEE6na75UnBLmVnSoZqtXb2q3YJAVxQdVo1xTWxPRQ', editable=False, max_length=100, unique=True),
        ),
    ]
