# Generated by Django 2.0.3 on 2018-11-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20181016_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='7zljpmBTz6BioY7P3BuaM6C1tVTsJPx1t3O1Wj7ZT4', editable=False, max_length=100, unique=True),
        ),
    ]
