# Generated by Django 2.0.3 on 2019-02-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20190203_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='4MxPms9HclbH3jP9M5HS5GU03fxVE8ocRqnov8kd8B', editable=False, max_length=100, unique=True),
        ),
    ]
