# Generated by Django 2.0.3 on 2021-01-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210118_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='kekXSdtlGKawCsGXuBPsORIedJBdjqeIUJ93c7Gxoa', editable=False, max_length=100, unique=True),
        ),
    ]
