# Generated by Django 2.0.3 on 2021-01-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210118_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='CXK2TLsPfRN4ftEtCKHWcBLxZE4AXMDH8q5RfOnzQm', editable=False, max_length=100, unique=True),
        ),
    ]
