# Generated by Django 2.0.3 on 2018-05-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20180524_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='piqb3PQOMpPCZi9r', editable=False, max_length=40, unique=True),
        ),
    ]
