# Generated by Django 2.0.3 on 2021-01-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20210119_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='xGLC5Zznixe5Qamka9siolvGjKH8R5Lye3Sv4jY0tH', editable=False, max_length=100, unique=True),
        ),
    ]
