# Generated by Django 2.0.3 on 2018-12-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20181227_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='B0Rn4LfbEK5gw1VtMY8VWdsNDDRag77LfbLVjDpUQJ', editable=False, max_length=100, unique=True),
        ),
    ]
