# Generated by Django 2.0.3 on 2018-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20180525_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='1fuvvXZEImiK2uBr', editable=False, max_length=40, unique=True),
        ),
    ]
