# Generated by Django 2.0.3 on 2018-12-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20181229_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='eBXG5KDdPXLeJp1jdAYF1db4qWc1tWDj8Kw5jZ1nSW', editable=False, max_length=100, unique=True),
        ),
    ]
