# Generated by Django 2.0.3 on 2018-12-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20181229_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingtransaction',
            name='trans_id',
            field=models.CharField(default='xZui1SQSfE44sNqciRwe1jlndVDFfKElgnDHkfddcQ', editable=False, max_length=100, unique=True),
        ),
    ]
