# Generated by Django 2.0.3 on 2021-01-03 01:16

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('description', models.CharField(max_length=50)),
                ('is_per_month', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Valid length is under 200 characters.', max_length=200)),
                ('posted_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('no_times_booked', models.IntegerField(default=0)),
                ('lodging_type', models.CharField(choices=[('1', 'Flat'), ('2', 'House/Apartment'), ('3', 'Paying guest'), ('4', 'Rooms'), ('5', 'Other')], max_length=2, verbose_name='type')),
                ('lodging_type_other', models.CharField(default='', max_length=100)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('floor_no', models.IntegerField(default=1)),
                ('furnishing', models.CharField(choices=[('1', 'Furnished'), ('2', 'Semi Furnished'), ('3', 'Unfurnished')], max_length=2)),
                ('facilities', models.CharField(default='', max_length=1000)),
                ('ground_floor', models.BooleanField(default=False)),
                ('top_floor', models.BooleanField(default=False)),
                ('available_from', models.DateField()),
                ('rent', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9][0-9]+$')])),
                ('area', models.CharField(max_length=12)),
                ('unit', models.CharField(choices=[('1', 'Sq. Gaj'), ('2', 'Sq. Feet'), ('3', 'Sq. Yds.'), ('4', 'Sq. Meter'), ('5', 'Acre'), ('6', 'Marla'), ('7', 'Kanal'), ('8', 'Ares'), ('9', 'Biswa'), ('10', 'Hectares')], max_length=2)),
                ('bathrooms', models.IntegerField(default=1)),
                ('rooms', models.IntegerField(default=1)),
                ('balconies', models.IntegerField(default=0)),
                ('halls', models.IntegerField(default=0)),
                ('advance_rent_of_months', models.PositiveIntegerField(default=1)),
                ('flooring', models.CharField(choices=[('1', 'Marble'), ('2', 'Vitrified Tile'), ('3', 'Vinyl'), ('4', 'Hardwood'), ('5', 'Granite'), ('6', 'Bamboo'), ('7', 'Concrete'), ('8', 'Laminate'), ('9', 'Linoleum'), ('10', 'Terrazzo'), ('11', 'Brick'), ('5', 'Other')], max_length=2)),
                ('flooring_other', models.CharField(default='', max_length=100)),
                ('additional_details', models.TextField(default='', max_length=2000)),
                ('title', models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_ ]+\\Z')])),
                ('slug', models.SlugField(editable=False, max_length=70, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('is_booked', models.BooleanField(default=False)),
                ('latlng', models.CharField(default='', max_length=100)),
                ('virtual_tour_link', models.CharField(default='', max_length=300)),
                ('last_confirmed', models.DateTimeField()),
                ('is_confirming', models.BooleanField(default=False)),
                ('room_number', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ('-available_from', 'posted_at'),
            },
        ),
    ]
