# Generated by Django 2.0.3 on 2019-01-04 21:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('description', models.CharField(max_length=50)),
                ('is_per_month', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommonlyUsedLodgingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_type', models.CharField(choices=[('F', 'Flat'), ('H', 'House/Apartment'), ('P', 'Paying guest'), ('R', 'Rooms'), ('O', 'Other')], default='R', max_length=2, verbose_name='type')),
                ('lodging_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('floor_no', models.IntegerField(default=1)),
                ('furnishing', models.CharField(choices=[('F', 'Furnished'), ('S', 'Semi Furnished'), ('U', 'Unfurnished')], default='U', max_length=2)),
                ('facilities', models.CharField(blank=True, max_length=1000, null=True)),
                ('ground_floor', models.BooleanField(default=False)),
                ('top_floor', models.BooleanField(default=False)),
                ('available_from', models.DateField(default=datetime.datetime(2019, 1, 4, 21, 17, 38, 449502))),
                ('rent', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9][0-9]+$')])),
                ('area', models.CharField(max_length=12)),
                ('unit', models.CharField(choices=[('1', 'Sq. Gaj'), ('2', 'Sq. Feet'), ('3', 'Sq. Yds.'), ('4', 'Sq. Meter'), ('5', 'Acre'), ('6', 'Marla'), ('7', 'Kanal'), ('8', 'Ares'), ('9', 'Biswa'), ('10', 'Hectares')], default='1', max_length=2)),
                ('bathrooms', models.IntegerField(default=1)),
                ('rooms', models.IntegerField(default=1)),
                ('balconies', models.IntegerField(default=0)),
                ('halls', models.IntegerField(default=0)),
                ('advance_rent_of_months', models.PositiveIntegerField(default=1)),
                ('flooring', models.CharField(blank=True, choices=[('M', 'Marble'), ('VT', 'Vitrified Tile'), ('V', 'Vinyl'), ('H', 'Hardwood'), ('G', 'Granite'), ('B', 'Bamboo'), ('C', 'Concrete'), ('L', 'Laminate'), ('LI', 'Linoleum'), ('T', 'Terrazzo'), ('BR', 'Brick'), ('O', 'Other')], max_length=2, null=True)),
                ('flooring_other', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_details', models.TextField(default='', help_text='Valid length is under 500 characters.', max_length=2000)),
                ('title', models.CharField(help_text='Max length is 70 characters. Only characters, digits, hyphen and underscore are allowed.', max_length=70, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_ ]+\\Z')])),
                ('slug', models.SlugField(editable=False, max_length=70, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('is_booked', models.BooleanField(default=False)),
                ('latlng', models.CharField(blank=True, max_length=100, null=True)),
                ('is_booking', models.BooleanField(default=False)),
                ('last_time_booking', models.DateTimeField(default=datetime.datetime(2019, 1, 4, 21, 17, 38, 449770))),
                ('virtual_tour_link', models.CharField(blank=True, max_length=300, null=True)),
                ('last_confirmed', models.DateTimeField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('is_confirmation_processing', models.BooleanField(default=False)),
                ('room_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-available_from',),
            },
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Valid length is under 200 characters.', max_length=200)),
                ('posted_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('no_times_booked', models.IntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.CharField(default='8L0ceBIB', max_length=20)),
            ],
            options={
                'ordering': ('posted_at',),
            },
        ),
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termsandconditions', to='lodging.CommonlyUsedLodgingModel')),
            ],
        ),
    ]
