# Generated by Django 2.0.3 on 2018-04-22 15:40

import apps.lodging.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonlyUsedLodgingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[(None, 'Choose location'), ('MN', 'Mukherjee nagar'), ('KA', 'Karol bagh'), ('MU', 'Munirka')], max_length=2)),
                ('lodging_type', models.CharField(choices=[(None, 'Choose type'), ('F', 'Flat'), ('H', 'House/Apartment'), ('P', 'Paying guest'), ('R', 'Rooms')], max_length=1, verbose_name='type')),
                ('total_floors', models.PositiveIntegerField(help_text='Ground floor is included in total floors.')),
                ('floor_no', models.IntegerField(help_text='Ground floor is zeroth floor.')),
                ('is_furnished', models.BooleanField()),
                ('is_kitchen_available', models.BooleanField()),
                ('is_parking_available', models.BooleanField()),
                ('ground_floor', models.BooleanField(default=False)),
                ('top_floor', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('available_from', models.DateField()),
                ('rent', models.PositiveIntegerField(db_index=True)),
                ('additional_details', models.TextField(blank=True, help_text='Valid characters are alphabets, digits, period and hyphen. Valid length is under 200 characters.', max_length=1000, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z .]*$')])),
                ('title', models.CharField(help_text='Valid characters are alphabets, digits, hyphen and underscore only. Valid length is under 70 characters.', max_length=70, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z _-]{10,}')])),
                ('slug', models.SlugField(editable=False, max_length=70, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
            ],
            options={
                'ordering': ('-available_from',),
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Maximum image size allowed is 5mb.', upload_to=apps.lodging.models.image_upload_path)),
                ('image_thumbnail', models.ImageField(help_text='Maximum image size allowed is 5mb.', upload_to=apps.lodging.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Valid characters are alphabets, digits, period and hyphen Valid length is under 200 characters.', max_length=200, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z ./,]{10,}$')])),
                ('posted_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('no_times_booked', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
