# Generated by Django 2.0.3 on 2018-08-01 00:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='flooring_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='area',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[1-9][0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='area_unit',
            field=models.CharField(choices=[('G', 'Gaj'), ('SF', 'Sq.Ft.'), ('SY', 'Sq.YDS.'), ('SM', 'Sq. METER'), ('A', 'Acres'), ('M', 'Marla'), ('B', 'Bigha'), ('K', 'Kanal'), ('GR', 'Grounds'), ('AR', 'Ares'), ('BI', 'Biswa'), ('GU', 'Guntha'), ('H', 'Hectares')], default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.date(2018, 8, 1)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='flooring',
            field=models.CharField(blank=True, choices=[('M', 'Marble'), ('VT', 'Vitrified Tile'), ('V', 'Vinyl'), ('H', 'Hardwood'), ('G', 'Granite'), ('B', 'Bamboo'), ('C', 'Concrete'), ('L', 'Laminate'), ('LI', 'Linoleum'), ('T', 'Terrazzo'), ('BR', 'Brick'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
