# Generated by Django 2.0.3 on 2018-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
