# Generated by Django 2.0.3 on 2018-08-15 15:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_auto_20180801_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.date(2018, 8, 15)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='booking_amount',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter in digits only', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='rent',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9][0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='security_deposit',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter in digits only', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='title',
            field=models.CharField(help_text='Make title as informative as possible', max_length=70, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z ]{10,}', message='Use alphabets and digits only. Valid length is under 70 characters.')]),
        ),
    ]
