# Generated by Django 2.0.3 on 2018-05-14 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_auto_20180513_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='additional_details',
            field=models.TextField(blank=True, help_text='Valid characters are alphabets, digits, and "-,./." only Valid length is under 500 characters.', max_length=500, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ,-/.]*$')]),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='title',
            field=models.CharField(help_text='Valid characters are alphabets, digits and "-_" only. Valid length is under 70 characters.', max_length=70, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z _-]{10,}')]),
        ),
    ]
