# Generated by Django 2.2.13 on 2021-01-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_auto_20210124_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='last_confirmed',
            field=models.FloatField(),
        ),
    ]
