# Generated by Django 2.0.3 on 2021-01-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_auto_20210103_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodging',
            name='room_number',
        ),
        migrations.AddField(
            model_name='lodging',
            name='reference',
            field=models.CharField(default='', max_length=10),
        ),
    ]
