# Generated by Django 2.0.3 on 2019-01-28 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_auto_20190104_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2019, 1, 28, 13, 31, 1, 478638)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 13, 31, 1, 478874)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='room_number',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='uid',
            field=models.CharField(default='MGjaOUTJ', max_length=20),
        ),
    ]
