# Generated by Django 2.0.3 on 2018-08-18 12:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0003_auto_20180815_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='advance_of_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='extra_charges',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter in digits only', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='extra_charges_description',
            field=models.CharField(blank=True, help_text='Valid length is under 200 characters.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.date(2018, 8, 18)),
        ),
    ]
