# Generated by Django 2.0.3 on 2018-05-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0003_auto_20180514_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_large',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
