# Generated by Django 2.2.13 on 2021-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0003_auto_20210210_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='facilities',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lodgingimage',
            name='tag',
            field=models.CharField(choices=[('0', 'Bedroom'), ('1', 'Hall'), ('2', 'Balcony'), ('3', 'Living Room'), ('4', 'Entrance'), ('5', 'Kitchen'), ('6', 'Bathroom'), ('7', 'Building'), ('8', 'Floor'), ('9', 'Outside View'), ('11', 'Dining Room'), ('10', 'Other')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='lodgingimage',
            name='tag_other',
            field=models.CharField(default='', max_length=100),
        ),
    ]
