# Generated by Django 2.0.3 on 2018-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0004_imagemodel_image_large'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_large',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
    ]
