# Generated by Django 2.0.3 on 2018-05-09 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0004_auto_20180507_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='address',
            field=models.CharField(help_text='Valid characters are alphabets, digits, period and hyphen Valid length is under 200 characters.', max_length=200, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z .\\/\\-\\,]{10,}$')]),
        ),
    ]
