# Generated by Django 2.2.13 on 2021-02-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0004_auto_20210221_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodging',
            old_name='hidden',
            new_name='idHidden',
        ),
    ]
