# Generated by Django 2.0.3 on 2021-01-18 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0004_auto_20210118_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingimage',
            name='lodging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodging.Lodging'),
        ),
    ]
