# Generated by Django 2.0.3 on 2019-02-03 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0004_auto_20190202_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2019, 2, 3, 14, 20, 52, 492758)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 3, 14, 20, 52, 492989)),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='uid',
            field=models.CharField(default='Kq5wDi8r', max_length=20),
        ),
    ]
