# Generated by Django 2.2.13 on 2021-02-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0005_auto_20210221_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodging',
            old_name='idHidden',
            new_name='isHidden',
        ),
    ]
