# Generated by Django 2.0.3 on 2018-05-22 10:20

import apps.lodging.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0005_auto_20180519_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=stdimage.models.StdImageField(help_text='Maximum image size allowed is 2mb.', upload_to=apps.lodging.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_thumbnail',
            field=models.ImageField(help_text='Maximum image size allowed is 2mb.', upload_to=apps.lodging.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='sublodging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodging.CommonlyUsedLodgingModel'),
        ),
    ]
