# Generated by Django 2.0.3 on 2018-08-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0005_auto_20180826_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonlyusedlodgingmodel',
            name='latlng',
        ),
    ]
