# Generated by Django 2.0.3 on 2018-05-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0006_auto_20180522_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodging',
            options={'ordering': ('posted_at',)},
        ),
    ]
