# Generated by Django 2.2.13 on 2021-04-15 00:15

import apps.lodging.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0007_lodging_bookedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingVRImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.lodging.models.lodging_vr_image_upload_path)),
                ('image_thumbnail', models.ImageField(upload_to=apps.lodging.models.lodging_vr_thumbnail_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('lodging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vr_images', to='lodging.Lodging')),
            ],
        ),
    ]
