# Generated by Django 2.0.3 on 2018-09-01 14:58

import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0007_auto_20180828_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.date(2018, 9, 1)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='slug',
            field=models.SlugField(editable=False, max_length=70, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
