# Generated by Django 2.0.3 on 2018-09-05 11:29

import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0008_auto_20180901_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonlyusedlodgingmodel',
            name='area_unit',
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 11, 29, 48, 406558)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='title',
            field=models.CharField(help_text='Max length is 70 characters. Only characters, digits, hyphen and underscore are allowed.', max_length=70, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_ ]+\\Z')]),
        ),
    ]
