# Generated by Django 2.0.3 on 2018-09-05 22:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0009_auto_20180905_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='area',
            field=models.CharField(max_length=12, validators=[django.core.validators.DecimalValidator(10, 6)]),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 9, 5, 22, 40, 22, 682066)),
        ),
    ]
