# Generated by Django 2.0.3 on 2018-09-14 22:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0010_auto_20180905_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='charge',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='lodging.CommonlyUsedLodgingModel'),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='additional_details',
            field=models.TextField(default='', help_text='Valid length is under 500 characters.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='area',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 9, 14, 22, 18, 18, 986583)),
        ),
    ]
