# Generated by Django 2.0.3 on 2018-10-01 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0012_auto_20180921_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='is_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 10, 56, 37, 709051)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 10, 1, 10, 56, 37, 708697)),
        ),
    ]
