# Generated by Django 2.0.3 on 2018-10-06 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0013_auto_20181001_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 10, 6, 21, 17, 25, 127043)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 21, 17, 25, 127416)),
        ),
        migrations.AddField(
            model_name='termandcondition',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termsandconditions', to='lodging.CommonlyUsedLodgingModel'),
        ),
    ]
