# Generated by Django 2.0.3 on 2018-10-16 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0015_auto_20181008_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='unit',
            field=models.CharField(choices=[('1', 'Sq. Gaj'), ('2', 'Sq. Feet'), ('3', 'Sq. Yds.'), ('4', 'Sq. Meter'), ('5', 'Acre'), ('6', 'Marla'), ('7', 'Kanal'), ('8', 'Ares'), ('9', 'Biswa'), ('10', 'Hectares')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 10, 16, 11, 56, 35, 130892)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 16, 11, 56, 35, 131189)),
        ),
    ]
