# Generated by Django 2.0.3 on 2018-11-17 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0016_auto_20181016_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 16, 23, 36, 848460)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 17, 16, 23, 36, 848709)),
        ),
    ]
