# Generated by Django 2.0.3 on 2018-12-29 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0019_auto_20181227_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='uid',
            field=models.CharField(default='0ou0ClR1', max_length=20),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 1, 1, 54, 951023)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 1, 1, 54, 951282)),
        ),
    ]
