# Generated by Django 2.0.3 on 2018-12-29 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0020_auto_20181229_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonlyusedlodgingmodel',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 1, 12, 29, 966221)),
        ),
        migrations.AlterField(
            model_name='commonlyusedlodgingmodel',
            name='last_time_booking',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 1, 12, 29, 966499)),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='uid',
            field=models.CharField(default='GmNJrHVN', max_length=20),
        ),
    ]
