# Generated by Django 2.2.13 on 2021-01-24 11:44

import apps.lodging.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('description', models.CharField(max_length=50)),
                ('is_per_month', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Valid length is under 200 characters.', max_length=200)),
                ('posted_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('no_times_booked', models.IntegerField(default=0)),
                ('lodging_type', models.CharField(choices=[('0', 'Flat'), ('1', 'House/Apartment'), ('2', 'Paying guest'), ('3', 'Rooms'), ('4', 'Other')], max_length=2, verbose_name='type')),
                ('lodging_type_other', models.CharField(default='', max_length=100)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('floor_no', models.IntegerField(default=1)),
                ('furnishing', models.CharField(choices=[('0', 'Furnished'), ('1', 'Semi Furnished'), ('2', 'Unfurnished')], max_length=2)),
                ('facilities', models.CharField(default='', max_length=1000)),
                ('ground_floor', models.BooleanField(blank=True, default=False)),
                ('top_floor', models.BooleanField(blank=True, default=False)),
                ('available_from', models.DateField(null=True)),
                ('rent', models.PositiveIntegerField()),
                ('area', models.CharField(max_length=12)),
                ('unit', models.CharField(choices=[('0', 'Sq. Gaj'), ('1', 'Sq. Feet'), ('2', 'Sq. Yds.'), ('3', 'Sq. Meter'), ('4', 'Acre'), ('5', 'Marla'), ('6', 'Kanal'), ('7', 'Ares'), ('8', 'Biswa'), ('9', 'Hectares')], max_length=2)),
                ('bathrooms', models.IntegerField(default=1)),
                ('rooms', models.IntegerField(default=1)),
                ('balconies', models.IntegerField(default=0)),
                ('halls', models.IntegerField(default=0)),
                ('advance_rent_of_months', models.PositiveIntegerField(default=1)),
                ('flooring', models.CharField(choices=[('0', 'Marble'), ('1', 'Vitrified Tile'), ('2', 'Vinyl'), ('3', 'Hardwood'), ('4', 'Granite'), ('5', 'Bamboo'), ('6', 'Concrete'), ('7', 'Laminate'), ('8', 'Linoleum'), ('9', 'Terrazzo'), ('10', 'Brick'), ('4', 'Other')], max_length=2)),
                ('flooring_other', models.CharField(default='', max_length=100)),
                ('additional_details', models.TextField(default='', max_length=2000)),
                ('title', models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_ ]+\\Z')])),
                ('slug', models.SlugField(editable=False, max_length=70, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('is_booked', models.BooleanField(default=False)),
                ('latlng', models.CharField(default='', max_length=100)),
                ('virtual_tour_link', models.CharField(default='', max_length=300)),
                ('last_confirmed', models.DateTimeField(auto_now=True)),
                ('is_confirming', models.BooleanField(default=False)),
                ('reference', models.CharField(default='', max_length=10)),
            ],
            options={
                'ordering': ('-available_from', 'posted_at'),
            },
        ),
        migrations.CreateModel(
            name='LodgingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.lodging.models.lodging_image_upload_path)),
                ('image_thumbnail', models.ImageField(upload_to=apps.lodging.models.lodging_thumbnail_upload_path)),
                ('image_mobile', models.ImageField(upload_to=apps.lodging.models.lodging_mobile_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(choices=[('0', 'Bedroom'), ('1', 'Hall'), ('2', 'Balcony'), ('3', 'Living Room'), ('4', 'Entrance'), ('5', 'Kitchen'), ('6', 'Bathroom'), ('7', 'Building'), ('8', 'Floor'), ('9', 'Outside View'), ('10', 'Other'), ('11', 'Dining Room')], max_length=2, null=True)),
                ('tag_other', models.CharField(blank=True, max_length=100, null=True)),
                ('lodging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodging.Lodging')),
            ],
        ),
    ]
