# Generated by Django 2.2.13 on 2021-01-24 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lodging', '0001_initial'),
        ('user', '0001_initial'),
        ('locations', '0002_auto_20210124_0153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodgings', to='user.Agreement'),
        ),
        migrations.AddField(
            model_name='lodging',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lodging',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='locations.Region'),
        ),
        migrations.AddField(
            model_name='charge',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='lodging.Lodging'),
        ),
    ]
