# Generated by Django 2.2.13 on 2021-12-05 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0009_auto_20210422_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='additional_details',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='bookedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='flooring_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='lodging_type',
            field=models.CharField(blank=True, choices=[('0', 'Flat'), ('1', 'House/Apartment'), ('2', 'Paying guest'), ('3', 'Rooms'), ('4', 'Other')], max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='lodging_type_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lodging',
            name='virtual_tour_link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='lodgingimage',
            name='tag_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
