# Generated by Django 2.2.13 on 2022-02-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0010_auto_20211205_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodging',
            name='is_booking',
            field=models.BooleanField(default=False),
        ),
    ]
