# Generated by Django 2.2.13 on 2021-04-13 02:56

from django.db import migrations
from django.contrib.auth.hashers import make_password

import os

from apps.user.models import CustomUserManager

def combine_names(apps, schema_editor):
    User = apps.get_model('user', 'User')
    user = User.objects.create(mobile_number=os.environ.get('SUPERUSER_MOBILE'))
    user.password = make_password(os.environ.get('SUPERUSER_PASSWORD'))
    user.is_superuser=True
    user.is_staff=True
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210129_2347'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
