# Generated by Django 2.2.13 on 2021-12-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_properties',
            field=models.ManyToManyField(blank=True, related_name='favorite_of', to='lodging.Lodging'),
        ),
    ]
