# Generated by Django 2.0.3 on 2018-05-24 13:36

import apps.roommate.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_auto_20180513_1451'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(help_text='Maximum image size allowed is 2mb.', upload_to=apps.roommate.models.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomieAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter correct value for rent', regex='^[1-9][0-9]+$')])),
                ('type', models.CharField(choices=[(None, 'Choose type'), ('R', 'Room(s)'), ('F', 'Flat')], max_length=1)),
                ('budget', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter correct value for budget', regex='^[1-9][0-9]+$')])),
                ('qualities', models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(message='Only digits, letters and follwing characters are allowed (.,\'"/)', regex='^[0-9a-zA-Z,.\'"/]$')])),
                ('available_from', models.DateField()),
                ('lodging_description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='image',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate.RoomieAd'),
        ),
        migrations.AddIndex(
            model_name='roomiead',
            index=models.Index(fields=['rent'], name='roommate_ro_rent_370b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='roomiead',
            index=models.Index(fields=['region'], name='roommate_ro_region__04ecd0_idx'),
        ),
        migrations.AddIndex(
            model_name='roomiead',
            index=models.Index(fields=['type'], name='roommate_ro_type_a610d0_idx'),
        ),
        migrations.AddIndex(
            model_name='roomiead',
            index=models.Index(fields=['budget'], name='roommate_ro_budget_abeb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='roomiead',
            index=models.Index(fields=['created_at'], name='roommate_ro_created_54d172_idx'),
        ),
    ]
