# Generated by Django 2.0.3 on 2018-05-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomiead',
            name='available_from',
        ),
    ]
