# Generated by Django 2.0.3 on 2018-07-08 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_roomiead_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomiead',
            name='gender',
            field=models.CharField(choices=[(None, 'Choose gender'), ('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomiead',
            name='lodging_description',
            field=models.TextField(help_text='e.g. Fully furnished 2BHK FLAT.', null=True, validators=[django.core.validators.RegexValidator(message='Only digits, letters and follwing characters are allowed (.,\'"/)', regex='^[0-9a-zA-Z ,.\'"/]*$')]),
        ),
    ]
