# Generated by Django 2.0.3 on 2018-05-25 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_remove_roomiead_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomiead',
            name='lodging_description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='Only digits, letters and follwing characters are allowed (.,\'"/)', regex='^[0-9a-zA-Z ,.\'"/]$')]),
        ),
        migrations.AlterField(
            model_name='roomiead',
            name='qualities',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(message='Only digits, letters and follwing characters are allowed (.,\'"/)', regex='^[0-9a-zA-Z ,.\'"/]$')]),
        ),
    ]
