# Generated by Django 2.0.3 on 2018-05-25 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0003_auto_20180525_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roommate.RoomieAd'),
        ),
        migrations.AlterField(
            model_name='roomiead',
            name='budget',
            field=models.CharField(blank=True, default=-1, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter correct value for budget', regex='^[1-9][0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='roomiead',
            name='lodging_description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='Only digits, letters and follwing characters are allowed (.,\'"/)', regex='^[0-9a-zA-Z ,.\'"/]*$')]),
        ),
        migrations.AlterField(
            model_name='roomiead',
            name='qualities',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(message='Only digits, letters and follwing characters are allowed (.,\'"/)', regex='^[0-9a-zA-Z ,.\'"/]*$')]),
        ),
        migrations.AlterField(
            model_name='roomiead',
            name='rent',
            field=models.CharField(blank=True, default=-1, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter correct value for rent', regex='^[1-9][0-9]+$')]),
        ),
    ]
